services:
  # Pytest unit testing
  test:
    build:
      context: backend
      dockerfile: Dockerfile_test
    environment:
        - MONGODB_URI=mongodb://mongodb:27017

  # App
  app:
    build:
      context: backend
      dockerfile: Dockerfile_app
    container_name: ciri-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    networks:
      - ciri-net
  # React client
  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: ciri-react
    ports:
      - "3000:3000"
    networks:
      - ciri-net
  # MongoDB
  mongodb:
    image: mongo:7.0.15
    container_name: ciri-mongo
    ports:
      - "27017:27017"
    networks:
      - ciri-net
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: unless-stopped

volumes:
  mongo_data:
  mongo_config:

networks:
  ciri-net: