FROM python:3
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install dependecies
COPY backend/requirements.txt ./requirements.txt
RUN python -m pip install -r requirements.txt

# copy the code
COPY . .

# run
CMD ["uvicorn", "backend.src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]