FROM python:3
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install dependecies
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY . .

# run the tests
CMD ["pytest", "tests/unit", "--maxfail=1", "--disable-warnings", "-v"]