FROM python:3
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install dependecies
COPY requiremenets.txt .
RUN python -m pip install -r requiremenets.txt

# copy the code
COPY . .

# run
CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]