# Stage 1 - install dependencies
FROM node:24.14.0-alpine AS dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Stage 2 - build the app for dev mode
FROM dependencies AS dev
COPY . .
ENV NODE_ENV=development
CMD ["npm", "run", "start:dev"]

# Stage 3 - build the app for production
FROM dependencies AS build
COPY . .
RUN npm run build

# Stage 4 - serve the production build
FROM node:24.14.0-alpine AS prod
ENV NODE_ENV=production
WORKDIR /app
RUN chown node:node /app
COPY package*.json ./
USER node
RUN npm ci --omit=dev
# Copy only the necessary files from the build stage
COPY --chown=node:node --from=build /app/dist ./dist
# Run the production build
CMD ["npm", "run", "start:prod"]
