# Stage 1 - install dependencies
FROM node:24-alpine AS dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Stage 2 - build the app for dev mode
FROM dependencies AS dev
COPY . .
ENV NODE_ENV=development
CMD ["npm", "run", "start"]
