FROM python:3
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

# install dependecies
COPY backend/requirements.txt ./requirements.txt
RUN python -m pip install -r requirements.txt

COPY ../backend .

# run the tests
CMD ["pytest", "backend/tests/unit", "--maxfail=1", "--disable-warnings", "-v"]