# Stage 1 - install dependencies
FROM node:24.14.0-alpine AS dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Stage 2 - build the app for dev mode
FROM dependencies AS dev
COPY . .
ENV NODE_ENV=development
CMD ["npm", "run", "start"]

# Stage 3 - build the app for production
FROM dependencies AS build
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
COPY . .
RUN npm run build

# Stage 4 - serve the production build
FROM nginx:alpine AS prod
# Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*
# Copy built frontend files from the build stage
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Run the production build
CMD ["nginx", "-g", "daemon off;"]