import 'reflect-metadata';

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { Logger } from '@nestjs/common';
import { DataSource, MigrationExecutor, QueryRunner } from 'typeorm';

import {
    databaseOptions,
    initializeMaintenanceDatabase,
} from './connection-options';
import {
    AzureBaseline1790985600000,
    infraDirectory,
    PerformanceSource1790985600001,
    RuntimeGrants1790985600002,
} from './migrations';

export function maintenanceDataSource(
    env: NodeJS.ProcessEnv = process.env,
): DataSource {
    return new DataSource({
        ...databaseOptions(env),
        migrations: [
            AzureBaseline1790985600000,
            PerformanceSource1790985600001,
            RuntimeGrants1790985600002,
        ],
    });
}

async function seedInitial(runner: QueryRunner): Promise<void> {
    const keys: Record<string, string[]> = {
        game_engines: ['name', 'version'],
        gpus: ['slug'],
        cpus: ['slug'],
        games: ['slug'],
        game_requirements: ['game_id', 'tier'],
        performance_records: [
            'game_id',
            'gpu_id',
            'cpu_id',
            'ram_gb',
            'ram_mhz',
            'res_width',
            'res_height',
            'settings',
            'upscaler',
            'upscaler_quality',
        ],
    };
    await runner.startTransaction();
    try {
        for (const table of Object.keys(keys)) {
            await runner.query(
                `CREATE TEMP TABLE ${table} (LIKE public.${table} INCLUDING DEFAULTS) ON COMMIT DROP`,
            );
            await runner.query(
                `ALTER TABLE pg_temp.${table} ALTER COLUMN id DROP DEFAULT, ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`,
            );
        }
        await runner.query('SET LOCAL search_path = pg_temp, public');
        await runner.query(
            readFileSync(
                resolve(infraDirectory, 'init-scripts/05-seed.sql'),
                'utf8',
            ),
        );
        for (const [table, key] of Object.entries(keys)) {
            // Remap staged foreign keys by stable values, never by fixture IDs.
            const relations =
                table === 'games'
                    ? ['game_engine_id']
                    : table === 'game_requirements' ||
                        table === 'performance_records'
                      ? ['game_id', 'cpu_id', 'gpu_id']
                      : [];
            for (const column of relations) {
                const target =
                    column === 'game_engine_id'
                        ? 'game_engines'
                        : `${column.slice(0, -3)}s`;
                const equality =
                    target === 'game_engines'
                        ? 'p.name = t.name AND p.version IS NOT DISTINCT FROM t.version'
                        : 'p.slug = t.slug';
                await runner.query(
                    `UPDATE pg_temp.${table} s SET ${column}=p.id FROM pg_temp.${target} t JOIN public.${target} p ON ${equality} WHERE s.${column}=t.id`,
                );
            }
            const columns = (await runner.query(
                "SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name<>'id' ORDER BY ordinal_position",
                [table],
            )) as { column_name: string }[];
            const list = columns
                .map(({ column_name }) => `"${column_name}"`)
                .join(',');
            const select = columns
                .map(({ column_name }) => `s."${column_name}"`)
                .join(',');
            const exists = key
                .map(
                    (column) =>
                        `p."${column}" IS NOT DISTINCT FROM s."${column}"`,
                )
                .join(' AND ');
            await runner.query(
                `INSERT INTO public.${table} (${list}) SELECT ${select} FROM pg_temp.${table} s WHERE NOT EXISTS (SELECT 1 FROM public.${table} p WHERE ${exists})`,
            );
        }
        await runner.commitTransaction();
    } catch (error) {
        await runner.rollbackTransaction();
        throw error;
    }
}

export async function runMaintenance(
    source: DataSource,
    command: string,
): Promise<boolean | void> {
    if (!['migrate', 'seed', 'show'].includes(command))
        throw new Error('Expected migrate, seed or show');
    const runner = source.createQueryRunner();
    await runner.connect();
    let locked = false;
    try {
        const result = (await runner.query(
            'SELECT pg_try_advisory_lock(1128878665, 3) AS acquired',
        )) as { acquired: boolean }[];
        locked = result[0].acquired;
        if (!locked) throw new Error('Database maintenance already running');
        const migrations = new MigrationExecutor(source, runner);
        migrations.transaction = 'all';
        if (command === 'migrate') await migrations.executePendingMigrations();
        if (command === 'seed') {
            if (await migrations.showMigrations())
                throw new Error('Run migrations before seed');
            await seedInitial(runner);
        }
        if (command === 'show') return migrations.showMigrations();
    } finally {
        if (locked)
            await runner.query('SELECT pg_advisory_unlock(1128878665, 3)');
        await runner.release();
    }
}

async function main(): Promise<void> {
    const logger = new Logger('DatabaseMaintenance');
    const deadline = setTimeout(() => {
        logger.error('Maintenance exceeded its execution budget');
        process.exit(1);
    }, 540000);
    deadline.unref();
    let source: DataSource | undefined;
    try {
        const command = process.argv[2];
        if (!['migrate', 'seed', 'show'].includes(command))
            throw new Error('Expected migrate, seed or show');
        source = maintenanceDataSource();
        await initializeMaintenanceDatabase(source);
        const pending = await runMaintenance(source, command);
        logger.log(
            command === 'show'
                ? `Pending migrations: ${String(pending)}`
                : `${command} completed`,
        );
    } catch {
        logger.error('Database maintenance failed; release is blocked');
        process.exitCode = 1;
    } finally {
        if (source?.isInitialized) await source.destroy();
        clearTimeout(deadline);
    }
}

if (require.main === module) void main();
