import { ClientGameDto } from './dto/client-game.dto';

export const MOCK_GAMES: ClientGameDto[] = [
    {
        id: 1,
        slug: 'kingdom-come-deliverance-2',
        name: 'Kingdom Come Deliverance 2',
        coverImageUrl: 'https://imgur.com/TqcyNA9.jpg',
        releaseDate: '2025-02-11',
        developer: 'Warhorse Studios',
        publisher: 'Deep Silver',
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 2,
        slug: 'god-of-war-2018',
        name: 'God of War (2018)',
        coverImageUrl: 'https://imgur.com/TxGGC6O.jpg',
        releaseDate: '2018-04-20',
        developer: 'Santa Monica Studio',
        publisher: 'Sony Interactive Entertainment',
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 3,
        slug: 'god-of-war-ragnarok',
        name: 'God of War Ragnarök',
        coverImageUrl: 'https://imgur.com/CyHn5T3.jpg',
        releaseDate: '2022-11-09',
        developer: 'Santa Monica Studio',
        publisher: 'Sony Interactive Entertainment',
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 4,
        slug: 'kingdom-come-deliverance',
        name: 'Kingdom Come: Deliverance',
        coverImageUrl: 'https://imgur.com/q1aVXnw.jpg',
        releaseDate: '2018-02-13',
        developer: 'Warhorse Studios',
        publisher: 'Deep Silver',
        supportsRayTracing: false,
        supportsDlss: false,
        supportsFsr: false,
    },
    {
        id: 5,
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        coverImageUrl: 'https://imgur.com/wNcAUoN.jpg',
        releaseDate: '2019-10-26',
        developer: 'Rockstar Games',
        publisher: 'Rockstar Games',
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 6,
        slug: 'black-myth-wukong',
        name: 'Black Myth: Wukong',
        coverImageUrl: 'https://imgur.com/yWszzjT.jpg',
        releaseDate: '2024-08-20',
        developer: 'Game Science',
        publisher: 'Game Science',
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 7,
        slug: 'assassins-creed-shadows',
        name: "Assassin's Creed Shadows",
        coverImageUrl: 'https://imgur.com/U5VoiQL.jpg',
        releaseDate: '2025-02-14',
        developer: 'Ubisoft',
        publisher: 'Ubisoft',
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 8,
        slug: 'the-last-of-us-part-1',
        name: 'The Last of Us Part I',
        coverImageUrl: 'https://imgur.com/uztXPuq.jpg',
        releaseDate: '2023-03-28',
        developer: 'Naughty Dog LLC',
        publisher: 'PlayStation Publishing LLC',
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 9,
        slug: 'the-last-of-us-part-2',
        name: 'The Last of Us Part II Remastered',
        coverImageUrl: 'https://imgur.com/P6jf9he.jpg',
        releaseDate: '2024-01-19',
        developer: 'Naughty Dog LLC',
        publisher: 'PlayStation Publishing LLC',
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
    },
    {
        id: 10,
        slug: 'cyberpunk-2077',
        name: 'Cyberpunk 2077',
        coverImageUrl: 'https://imgur.com/VDUcpgp.jpg',
        releaseDate: '2020-12-10',
        developer: 'CD PROJEKT RED',
        publisher: 'CD PROJEKT RED',
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
    },
];
