import { ClientGameDto } from './dto/client-game.dto';

export const MOCK_GAMES: ClientGameDto[] = [
    {
        id: 1,
        slug: 'kingdom-come-deliverance-2',
        name: 'Kingdom Come Deliverance 2',
        coverImageUrl: 'https://imgur.com/TqcyNA9.jpg',
        releaseDate: '2025-02-11',
        developer: 'Warhorse Studios',
        publisher: 'Deep Silver',
        genre: 'RPG',
        description:
            'A story-driven open-world RPG that immerses you in an epic adventure in the Holy Roman Empire.',
        tags: ['rpg', 'medieval', 'open-world'],
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 3,
    },
    {
        id: 2,
        slug: 'god-of-war-2018',
        name: 'God of War (2018)',
        coverImageUrl: 'https://imgur.com/TxGGC6O.jpg',
        releaseDate: '2018-04-20',
        developer: 'Santa Monica Studio',
        publisher: 'Sony Interactive Entertainment',
        genre: 'Action-Adventure',
        description:
            'Kratos, having long ago taken his vengeance against the gods of Olympus, now lives as a man in the realm of Norse gods and monsters.',
        tags: ['action', 'adventure', 'norse'],
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: false,
        trendingRank: null,
    },
    {
        id: 3,
        slug: 'god-of-war-ragnarok',
        name: 'God of War Ragnarök',
        coverImageUrl: 'https://imgur.com/CyHn5T3.jpg',
        releaseDate: '2022-11-09',
        developer: 'Santa Monica Studio',
        publisher: 'Sony Interactive Entertainment',
        genre: 'Action-Adventure',
        description:
            'Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.',
        tags: ['action', 'adventure', 'norse'],
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 4,
    },
    {
        id: 4,
        slug: 'kingdom-come-deliverance',
        name: 'Kingdom Come: Deliverance',
        coverImageUrl: 'https://imgur.com/q1aVXnw.jpg',
        releaseDate: '2018-02-13',
        developer: 'Warhorse Studios',
        publisher: 'Deep Silver',
        genre: 'RPG',
        description:
            "You're Henry, the son of a blacksmith. Thrust into a raging civil war, you watch helplessly as invaders storm your village and slaughter your friends and family.",
        tags: ['rpg', 'medieval', 'realistic'],
        supportsRayTracing: false,
        supportsDlss: false,
        supportsFsr: false,
        supportsXeSS: false,
        isTrending: false,
        trendingRank: null,
    },
    {
        id: 5,
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        coverImageUrl: 'https://imgur.com/wNcAUoN.jpg',
        releaseDate: '2019-10-26',
        developer: 'Rockstar Games',
        publisher: 'Rockstar Games',
        genre: 'Action-Adventure',
        description:
            'Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.',
        tags: ['western', 'open-world', 'rockstar'],
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 5,
    },
    {
        id: 6,
        slug: 'black-myth-wukong',
        name: 'Black Myth: Wukong',
        coverImageUrl: 'https://imgur.com/yWszzjT.jpg',
        releaseDate: '2024-08-20',
        developer: 'Game Science',
        publisher: 'Game Science',
        genre: 'Action RPG',
        description:
            'Black Myth: Wukong is an action RPG rooted in Chinese mythology.',
        tags: ['action', 'rpg', 'mythology'],
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 2,
    },
    {
        id: 7,
        slug: 'assassins-creed-shadows',
        name: "Assassin's Creed Shadows",
        coverImageUrl: 'https://imgur.com/U5VoiQL.jpg',
        releaseDate: '2025-02-14',
        developer: 'Ubisoft',
        publisher: 'Ubisoft',
        genre: 'Action-Adventure',
        description:
            'Live the intertwined stories of Naoe, an adept shinobi Assassin from Iga Province, and Yasuke, the powerful African samurai of historical legend.',
        tags: ['assassin', 'stealth', 'japan'],
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 6,
    },
    {
        id: 8,
        slug: 'the-last-of-us-part-1',
        name: 'The Last of Us Part I',
        coverImageUrl: 'https://imgur.com/uztXPuq.jpg',
        releaseDate: '2023-03-28',
        developer: 'Naughty Dog LLC',
        publisher: 'PlayStation Publishing LLC',
        genre: 'Action-Adventure',
        description:
            'In a ravaged civilization, where infected and hardened survivors run wild, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone.',
        tags: ['action', 'zombies', 'story-rich'],
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: false,
        trendingRank: null,
    },
    {
        id: 9,
        slug: 'the-last-of-us-part-2',
        name: 'The Last of Us Part II Remastered',
        coverImageUrl: 'https://imgur.com/P6jf9he.jpg',
        releaseDate: '2024-01-19',
        developer: 'Naughty Dog LLC',
        publisher: 'PlayStation Publishing LLC',
        genre: 'Action-Adventure',
        description:
            'Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming.',
        tags: ['action', 'zombies', 'emotionally-charged'],
        supportsRayTracing: false,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 7,
    },
    {
        id: 10,
        slug: 'cyberpunk-2077',
        name: 'Cyberpunk 2077',
        coverImageUrl: 'https://imgur.com/VDUcpgp.jpg',
        releaseDate: '2020-12-10',
        developer: 'CD PROJEKT RED',
        publisher: 'CD PROJEKT RED',
        genre: 'Action RPG',
        description:
            'Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.',
        tags: ['cyberpunk', 'open-world', 'fps'],
        supportsRayTracing: true,
        supportsDlss: true,
        supportsFsr: true,
        supportsXeSS: true,
        isTrending: true,
        trendingRank: 1,
    },
];
