name: CI
# Trigger only
on:
  pull_request:
    paths-ignore:
      - '../../README.md' # Ignore changes to README files - no need to recheck the code
    branches:
      - main

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run pytest
        run: docker compose run --build --rm test